services:
  bandit:
    build:
      context: .
      dockerfile: Dockerfile
    image: bandit:latest
    working_dir: /app
    entrypoint: ["uv", "run", "bandit", "--country_code", "UK"]
    tty: true


