services:
  bandit:
    build:
      context: .
      dockerfile: Dockerfile
    image: bandit:latest
    working_dir: /app
    entrypoint: ["uv", "run", "bandit"]
    command:
     - "--country_code"
     - "${COUNTRY_CODE}"
    environment:
     - COUNTRY_CODE=UK
    tty: true


